version: '3'
services:
  server:
    build: ./server
    container_name: 'OkatronServer'
    tty: true
    stdin_open: true
    ports:
      - "8050:8050"
    networks:
      okatronAI:
        ipv4_address: 172.18.0.10
    volumes:
      - ./resouece:/resource
      - ./resource/config:/resource/config
      - ./resource/model:/resource/model
    devices:
      - "/dev/video0:/dev/video0"


  fastapi:
    build: ./FastAPI
    container_name: 'FastAPI'
    tty: true
    stdin_open: true
    ports:
      - "8000:8000"
    networks:
      okatronAI:
        ipv4_address: 172.18.0.20
    volumes:
      - ./FastAPI:/FastAPI

networks:
  okatronAI:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16