version: '3'
services:
  server:
    build: ./server
    container_name: 'OkatronServer'
    tty: true
    stdin_open: true
    network_mode: "host"
    ports:
      - "8000:8000"
    volumes:
      - ./resource:/resource
      - ./resource/config:/resource/config
      - ./resource/model:/resource/model
      - ./server:/server