version: '3'
services:
  server:
    build: ./server
    container_name: 'OkatronServer'
    tty: true
    stdin_open: true
    network_mode: "host"
    volumes:
      - ./server:/server
      - ./resouece:/resouece
    working_dir: /server


  # fastapi:
  #   build: ./FastAPI
  #   container_name: 'FastAPI'
  #   tty: true
  #   stdin_open: true
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./FastAPI:/FastAPI
  #   working_dir: /FastAPI
    # command: uvicorn api.main:app --reload --host 0.0.0.0 --port 8080 --workers 10