version: '3'
services:
  server:
    build: ./server
    container_name: 'OkatronServer'
    tty: true
    stdin_open: true
    ports:
      - "8050:8050"
    volumes:
      - ./resource:/resource
      - ./resource/config:/resource/config
      - ./resource/model:/resource/model
      - ./server:/server