version: '3'
services:
  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8080:8080"
    volumes:
      - .:/fastapi
    working_dir: /fastapi
    command: uvicorn api.main:app --reload --host 0.0.0.0 --port 8080 --workers 10
