base:
  mode: "Auto"

camera:
  id: 0
  width: 320
  height: 240
  fps: 30

controller:
  span: 1

lost:
  time: 2

yolov5:
  weight: yolov5n.pt
  image:
    - 320
    - 320
  conf: 0.45
  iou: 0.45
  det_class: 0